// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SlMMLTouchApp {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegateIPad")]
	public partial class AppDelegateIPad {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UITextView __mt_mml_text;
		
		private MonoTouch.UIKit.UIButton __mt_play_button;
		
		private MonoTouch.UIKit.UIView __mt_touch_surface;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mml_text")]
		private MonoTouch.UIKit.UITextView mml_text {
			get {
				this.__mt_mml_text = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("mml_text")));
				return this.__mt_mml_text;
			}
			set {
				this.__mt_mml_text = value;
				this.SetNativeField("mml_text", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("play_button")]
		private MonoTouch.UIKit.UIButton play_button {
			get {
				this.__mt_play_button = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("play_button")));
				return this.__mt_play_button;
			}
			set {
				this.__mt_play_button = value;
				this.SetNativeField("play_button", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("touch_surface")]
		private MonoTouch.UIKit.UIView touch_surface {
			get {
				this.__mt_touch_surface = ((MonoTouch.UIKit.UIView)(this.GetNativeField("touch_surface")));
				return this.__mt_touch_surface;
			}
			set {
				this.__mt_touch_surface = value;
				this.SetNativeField("touch_surface", value);
			}
		}
	}
}
